<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admins_model extends CI_Model
{

    public $table = 'admins';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function admins_json() {
        $this->datatables->select('id,username,password,name,email,role_id,status,last_login,ip,email_verified_at,email_activator,email_activator_code,remember_token,remember_token_code,created_at,updated_at');
        $this->datatables->from('admins');
        //add this line for join
        //$this->datatables->join('table2', 'admins.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admins/read/$1'),'Read')." | ".anchor(site_url('admins/update/$1'),'Update')." | ".anchor(site_url('admins/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('role_id', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('ip', $q);
	$this->db->or_like('email_verified_at', $q);
	$this->db->or_like('email_activator', $q);
	$this->db->or_like('email_activator_code', $q);
	$this->db->or_like('remember_token', $q);
	$this->db->or_like('remember_token_code', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('role_id', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('last_login', $q);
	$this->db->or_like('ip', $q);
	$this->db->or_like('email_verified_at', $q);
	$this->db->or_like('email_activator', $q);
	$this->db->or_like('email_activator_code', $q);
	$this->db->or_like('remember_token', $q);
	$this->db->or_like('remember_token_code', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Admins_model.php */
/* Location: ./application/models/Admins_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-10 11:57:50 */
/* http://harviacode.com */
