<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class History_model extends CI_Model
{

    public $table = 'history';
    public $id = 'history_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('history_id,history_tabel,history_tabel_id,history_detail,history_user_name,history_time');
        $this->datatables->from('history');
        //add this line for join
        //$this->datatables->join('table2', 'history.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('history/read/$1'),'Read')." | ".anchor(site_url('history/update/$1'),'Update')." | ".anchor(site_url('history/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'history_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('history_id', $q);
	$this->db->or_like('history_tabel', $q);
	$this->db->or_like('history_tabel_id', $q);
	$this->db->or_like('history_detail', $q);
	$this->db->or_like('history_user_name', $q);
	$this->db->or_like('history_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('history_id', $q);
	$this->db->or_like('history_tabel', $q);
	$this->db->or_like('history_tabel_id', $q);
	$this->db->or_like('history_detail', $q);
	$this->db->or_like('history_user_name', $q);
	$this->db->or_like('history_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file History_model.php */
/* Location: ./application/models/History_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-08-11 04:16:13 */
/* http://harviacode.com */